### ISSUE TITLE
[Bug]: Unable to configure memory limit

### ISSUE THREAD

**Issue by MichaelLogutov** [testcontainers/testcontainers-dotnet#1090]
### Testcontainers version

3.7.0

### Using the latest Testcontainers version?

Yes

### Host OS

Windows

### Host arch

x64

### .NET version

8.0

### Docker version

```shell
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:44 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.26.1 (131620)
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:02 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.25
  GitCommit:        d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client:
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.0-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.3-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  0.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.10
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.2.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 24
  Running: 0
  Paused: 0
  Stopped: 24
 Images: 38
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 3.829GiB
 Name: docker-desktop
 ID: d148ec48-a8e8-4270-a982-10e4570c90ce
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

### What happened?

Using `HostConfig.Memory` to configure memory limit gets me an error:

```
using DotNet.Testcontainers.Builders;

namespace Sandbox;

class Program
{
    static async Task Main()
    {
        await using var container = new ContainerBuilder()
            .WithImage("alpine")
            .WithCreateParameterModifier(x => x.HostConfig.Memory = 2 * 1024 * 1024)
            .Build();

        await container.StartAsync();
    }
}
```

### Relevant log output

```shell
[testcontainers.org 00:00:00.09] Connected to Docker:
  Host: npipe://./pipe/docker_engine
  Server Version: 24.0.7
  Kernel Version: 5.10.102.1-microsoft-standard-WSL2
  API Version: 1.43
  Operating System: Docker Desktop
  Total Memory: 3.83 GB
[testcontainers.org 00:00:00.22] Docker container 9fa88b052728 created
[testcontainers.org 00:00:00.25] Start Docker container 9fa88b052728
[testcontainers.org 00:00:01.56] Wait for Docker container 9fa88b052728 to complete readiness checks
[testcontainers.org 00:00:01.57] Docker container 9fa88b052728 ready
Unhandled exception. Docker.DotNet.DockerApiException: Docker API responded with status code=BadRequest, response={"message":"Minimum memory limit allowed is 6MB"}

   at Docker.DotNet.DockerClient.HandleIfErrorResponseAsync(HttpStatusCode statusCode, HttpResponseMessage response, IEnumerable`1 handlers)
   at Docker.DotNet.DockerClient.MakeRequestAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
   at Docker.DotNet.ContainerOperations.CreateContainerAsync(CreateContainerParameters parameters, CancellationToken cancellationToken)
   at DotNet.Testcontainers.Clients.DockerContainerOperations.RunAsync(IContainerConfiguration configuration, CancellationToken ct)
   at DotNet.Testcontainers.Clients.TestcontainersClient.RunAsync(IContainerConfiguration configuration, CancellationToken ct)
   at DotNet.Testcontainers.Containers.DockerContainer.UnsafeCreateAsync(CancellationToken ct)
   at DotNet.Testcontainers.Containers.DockerContainer.StartAsync(CancellationToken ct)
   at Sandbox.Program.Main() in C:\GIT\Sandbox\Sandbox\Program.cs:line 14
   at Sandbox.Program.Main() in C:\GIT\Sandbox\Sandbox\Program.cs:line 14
   at Sandbox.Program.<Main>()
```

**Comment by HofmeisterAn** [comment]
This is not an issue in Testcontainers. Unfortunately, this is a limitation of Docker and is [documented](https://docs.docker.com/config/containers/resource_constraints/).

> If you set this option, the minimum allowed value is 6m (6 megabytes). That is, you must set the value to at least 6 megabytes.

You will find more information in the related pull request as well (https://github.com/moby/moby/pull/41168).

**Comment by MichaelLogutov** [comment]
I've set value to 2GB (see the code). Are you sure it's not the testcontainer proxy container issue?

**Comment by HofmeisterAn** [comment]
> I've set value to 2GB (see the code).

Nope, you did not. You set it to 2MB.

According to the API docs the unit is bytes.

> Memory limit in bytes.

**Comment by MichaelLogutov** [comment]
🤦
My, mistake, sorry.
