### ISSUE TITLE
[Bug]: Can't connect to Oracle container via EF Core

### ISSUE THREAD

**Issue by dadyarri** [testcontainers/testcontainers-dotnet#1108]
### Testcontainers version

3.7.0

### Using the latest Testcontainers version?

Yes

### Host OS

Windows

### Host arch

x86_64

### .NET version

8.0.101

### Docker version

```shell
Client:
 Cloud integration: v1.0.35+desktop.10
 Version:           25.0.2
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Thu Feb  1 00:24:09 2024
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.27.1 (136059)
 Engine:
  Version:          25.0.2
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       fce6e0c
  Built:            Thu Feb  1 00:23:17 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client:
 Version:    25.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.3-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.22
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.3.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 10
 Server Version: 25.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.133.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 20
 Total Memory: 15.5GiB
 Name: docker-desktop
 ID: 366475ec-eb36-4cb1-9168-a56e33b8b662
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

### What happened?

When i'm trying to connect to oracle database with default parameters i'm getting error ORA-01435 (user does not exist), although if i pause execution of tests and try to connect to the same database via external tool (datagrip in my case), i can do that successfully with same credentials as in default config of the module

### Relevant log output

```shell
Oracle.ManagedDataAccess.Client.OracleException: ORA-01435: user does not exist

Oracle.ManagedDataAccess.Client.OracleException
ORA-01435: user does not exist
ORA-06512: at  line 8
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreatedAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreatedAsync(CancellationToken cancellationToken)
   at FlexLabs.EntityFrameworkCore.Upsert.IntegrationTests.DatabaseInitializerFixture.InitializeAsync() ...
```

### Additional information

```csharp
protected override IContainer BuildContainer()
                => new OracleBuilder()
                    .Build();
```

Both variants to connect doesn't work:

```csharp
var connectionString = (TestContainer as IDatabaseContainer)?.GetConnectionString();
builder.UseOracle(connectionString);
```

```csharp
var connectionString = (TestContainer as IDatabaseContainer)?.GetConnectionString();
var port = Regex.Matches(connectionString!, @"PORT=(\d+)").First().Groups[1].Value;
builder.UseOracle($"Data Source=127.0.0.1:{port}/XEPDB1;User Id=oracle;Password=oracle");
```

**Comment by HofmeisterAn** [comment]
I am sorry; I cannot reproduce it. I changed our WeatherForecast example, which utilizes EF, from SQL Edge to Oracle and had no issues. Do you have a reproducer?

    Microsoft (R) Test Execution Command Line Tool Version 17.8.0 (x64)
    Copyright (c) Microsoft Corporation.  All rights reserved.         

    Starting test execution, please wait...
    A total of 1 test files matched the specified pattern.

    Passed!  - Failed:     0, Passed:     2, Skipped:     0, Total:     2, Duration: 160 ms - WeatherForecast.InProcess.Tests.dll (net8.0)
    
```diff
diff --git a/examples/WeatherForecast/Directory.Packages.props b/examples/WeatherForecast/Directory.Packages.props
index edbae96..1d92417 100644
--- a/examples/WeatherForecast/Directory.Packages.props
+++ b/examples/WeatherForecast/Directory.Packages.props
@@ -4,13 +4,13 @@
     <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
   </PropertyGroup>
   <ItemGroup>
-    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.1"/>
+    <PackageVersion Include="Oracle.EntityFrameworkCore" Version="8.21.121" />
     <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="8.0.1"/>
     <PackageVersion Include="Microsoft.Fast.Components.FluentUI" Version="3.5.4"/>
     <!-- Unit and integration test dependencies: -->
     <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.8.0"/>
     <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.1"/>
-    <PackageVersion Include="Testcontainers.SqlEdge" Version="3.7.0"/>
+    <PackageVersion Include="Testcontainers.Oracle" Version="3.7.0"/>
     <PackageVersion Include="xunit.runner.visualstudio" Version="2.5.6"/>
     <PackageVersion Include="xunit" Version="2.6.5"/>
     <!-- Third-party client dependencies to connect and interact with the containers: -->
diff --git a/examples/WeatherForecast/src/WeatherForecast/DatabaseContainer.cs b/examples/WeatherForecast/src/WeatherForecast/DatabaseContainer.cs
index 9f655a9..d16706b 100644
--- a/examples/WeatherForecast/src/WeatherForecast/DatabaseContainer.cs
+++ b/examples/WeatherForecast/src/WeatherForecast/DatabaseContainer.cs
@@ -2,20 +2,20 @@ namespace WeatherForecast;
 
 public sealed class DatabaseContainer : IHostedService
 {
-  private readonly SqlEdgeContainer _sqlEdgeContainer = new SqlEdgeBuilder().Build();
+  private readonly OracleContainer _oracleContainer = new OracleBuilder().Build();
 
   public Task StartAsync(CancellationToken cancellationToken)
   {
-    return _sqlEdgeContainer.StartAsync(cancellationToken);
+    return _oracleContainer.StartAsync(cancellationToken);
   }
 
   public Task StopAsync(CancellationToken cancellationToken)
   {
-    return _sqlEdgeContainer.StopAsync(cancellationToken);
+    return _oracleContainer.StopAsync(cancellationToken);
   }
 
   public string GetConnectionString()
   {
-    return _sqlEdgeContainer.GetConnectionString();
+    return _oracleContainer.GetConnectionString();
   }
 }
diff --git a/examples/WeatherForecast/src/WeatherForecast/Program.cs b/examples/WeatherForecast/src/WeatherForecast/Program.cs
index eaed380..004d65e 100644
--- a/examples/WeatherForecast/src/WeatherForecast/Program.cs
+++ b/examples/WeatherForecast/src/WeatherForecast/Program.cs
@@ -14,13 +14,13 @@ if (string.IsNullOrWhiteSpace(connectionString))
   builder.Services.AddDbContext<WeatherDataContext>((services, options) =>
   {
     var databaseContainer = services.GetRequiredService<DatabaseContainer>();
-    options.UseSqlServer(databaseContainer.GetConnectionString());
+    options.UseOracle(databaseContainer.GetConnectionString());
   });
 }
 else
 {
   // The application configuration includes a database connection string, use it to establish a connection and seed the database.
-  builder.Services.AddDbContext<WeatherDataContext>((_, options) => options.UseSqlServer(connectionString));
+  builder.Services.AddDbContext<WeatherDataContext>((_, options) => options.UseOracle(connectionString));
 }
 
 builder.Services.AddScoped<IWeatherDataReadOnlyRepository, WeatherDataReadOnlyContext>();
diff --git a/examples/WeatherForecast/src/WeatherForecast/Usings.cs b/examples/WeatherForecast/src/WeatherForecast/Usings.cs
index d698b74..6d075e3 100644
--- a/examples/WeatherForecast/src/WeatherForecast/Usings.cs
+++ b/examples/WeatherForecast/src/WeatherForecast/Usings.cs
@@ -9,7 +9,7 @@ global using Microsoft.Extensions.Configuration;
 global using Microsoft.Extensions.DependencyInjection;
 global using Microsoft.Extensions.Hosting;
 global using Microsoft.Fast.Components.FluentUI;
-global using Testcontainers.SqlEdge;
+global using Testcontainers.Oracle;
 global using WeatherForecast;
 global using WeatherForecast.Contexts;
 global using WeatherForecast.Entities;
diff --git a/examples/WeatherForecast/src/WeatherForecast/WeatherForecast.csproj b/examples/WeatherForecast/src/WeatherForecast/WeatherForecast.csproj
index 28dea35..5f6dc15 100644
--- a/examples/WeatherForecast/src/WeatherForecast/WeatherForecast.csproj
+++ b/examples/WeatherForecast/src/WeatherForecast/WeatherForecast.csproj
@@ -3,9 +3,9 @@
     <TargetFrameworks>net8.0</TargetFrameworks>
   </PropertyGroup>
   <ItemGroup>
-    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer"/>
+    <PackageReference Include="Oracle.EntityFrameworkCore"/>
     <PackageReference Include="Microsoft.Fast.Components.FluentUI"/>
-    <PackageReference Include="Testcontainers.SqlEdge"/>
+    <PackageReference Include="Testcontainers.Oracle"/>
   </ItemGroup>
   <ItemGroup>
     <ProjectReference Include="../WeatherForecast.Contexts/WeatherForecast.Contexts.csproj"/>
diff --git a/examples/WeatherForecast/tests/WeatherForecast.InProcess.Tests/Usings.cs b/examples/WeatherForecast/tests/WeatherForecast.InProcess.Tests/Usings.cs
index 467c50c..9c515b1 100644
--- a/examples/WeatherForecast/tests/WeatherForecast.InProcess.Tests/Usings.cs
+++ b/examples/WeatherForecast/tests/WeatherForecast.InProcess.Tests/Usings.cs
@@ -8,7 +8,7 @@ global using System.Threading.Tasks;
 global using JetBrains.Annotations;
 global using Microsoft.AspNetCore.Mvc.Testing;
 global using Microsoft.Extensions.DependencyInjection;
-global using Testcontainers.SqlEdge;
+global using Testcontainers.Oracle;
 global using WeatherForecast.Entities;
 global using WeatherForecast.Repositories;
 global using Xunit;
diff --git a/examples/WeatherForecast/tests/WeatherForecast.InProcess.Tests/WeatherForecastTest.cs b/examples/WeatherForecast/tests/WeatherForecast.InProcess.Tests/WeatherForecastTest.cs
index 5ec3074..9e2aa9d 100644
--- a/examples/WeatherForecast/tests/WeatherForecast.InProcess.Tests/WeatherForecastTest.cs
+++ b/examples/WeatherForecast/tests/WeatherForecast.InProcess.Tests/WeatherForecastTest.cs
@@ -3,16 +3,16 @@ namespace WeatherForecast.InProcess.Tests;
 [UsedImplicitly]
 public sealed class WeatherForecastTest : IAsyncLifetime
 {
-  private readonly SqlEdgeContainer _sqlEdgeContainer = new SqlEdgeBuilder().Build();
+  private readonly OracleContainer _oracleContainer = new OracleBuilder().Build();
 
   public Task InitializeAsync()
   {
-    return _sqlEdgeContainer.StartAsync();
+    return _oracleContainer.StartAsync();
   }
 
   public Task DisposeAsync()
   {
-    return _sqlEdgeContainer.DisposeAsync().AsTask();
+    return _oracleContainer.DisposeAsync().AsTask();
   }
 
   public sealed class Api : IClassFixture<WeatherForecastTest>, IDisposable
@@ -30,7 +30,7 @@ public sealed class WeatherForecastTest : IAsyncLifetime
       Environment.SetEnvironmentVariable("ASPNETCORE_URLS", "https://+");
       Environment.SetEnvironmentVariable("ASPNETCORE_Kestrel__Certificates__Default__Path", "certificate.crt");
       Environment.SetEnvironmentVariable("ASPNETCORE_Kestrel__Certificates__Default__Password", "password");
-      Environment.SetEnvironmentVariable("ConnectionStrings__DefaultConnection", weatherForecastTest._sqlEdgeContainer.GetConnectionString());
+      Environment.SetEnvironmentVariable("ConnectionStrings__DefaultConnection", weatherForecastTest._oracleContainer.GetConnectionString());
       _webApplicationFactory = new WebApplicationFactory<Program>();
       _serviceScope = _webApplicationFactory.Services.GetRequiredService<IServiceScopeFactory>().CreateScope();
       _httpClient = _webApplicationFactory.CreateClient();
diff --git a/examples/WeatherForecast/tests/WeatherForecast.Tests/Usings.cs b/examples/WeatherForecast/tests/WeatherForecast.Tests/Usings.cs
index c10a6ec..f16a09d 100644
--- a/examples/WeatherForecast/tests/WeatherForecast.Tests/Usings.cs
+++ b/examples/WeatherForecast/tests/WeatherForecast.Tests/Usings.cs
@@ -14,6 +14,6 @@ global using DotNet.Testcontainers.Containers;
 global using DotNet.Testcontainers.Images;
 global using DotNet.Testcontainers.Networks;
 global using JetBrains.Annotations;
-global using Testcontainers.SqlEdge;
+global using Testcontainers.Oracle;
 global using WeatherForecast.Entities;
 global using Xunit;
diff --git a/examples/WeatherForecast/tests/WeatherForecast.Tests/WeatherForecastContainer.cs b/examples/WeatherForecast/tests/WeatherForecast.Tests/WeatherForecastContainer.cs
index cf92f34..05c03c3 100644
--- a/examples/WeatherForecast/tests/WeatherForecast.Tests/WeatherForecastContainer.cs
+++ b/examples/WeatherForecast/tests/WeatherForecast.Tests/WeatherForecastContainer.cs
@@ -22,12 +22,12 @@ public sealed class WeatherForecastContainer : HttpClient, IAsyncLifetime
   {
     const string weatherForecastStorage = "weatherForecastStorage";
 
-    const string connectionString = $"Server={weatherForecastStorage};User Id={SqlEdgeBuilder.DefaultUsername};Password={SqlEdgeBuilder.DefaultPassword};Database={SqlEdgeBuilder.DefaultDatabase};TrustServerCertificate=True";
+    const string connectionString = $"Server={weatherForecastStorage};User Id={OracleBuilder.DefaultUsername};Password={OracleBuilder.DefaultPassword};Database={OracleBuilder.DefaultDatabase};TrustServerCertificate=True";
 
     _weatherForecastNetwork = new NetworkBuilder()
       .Build();
 
-    _sqlEdgeContainer = new SqlEdgeBuilder()
+    _sqlEdgeContainer = new OracleBuilder()
       .WithNetwork(_weatherForecastNetwork)
       .WithNetworkAliases(weatherForecastStorage)
       .Build();
```

**Comment by dadyarri** [comment]
Hi, thanks for answer! With your example i have no problems either. I can reproduce it in https://github.com/dadyarri/FlexLabs.Upsert (branch support-oracle, IntegrationTests project). Exception is raised from context.Database.EnsureCreated, seems like example project doesn't call this method

**Comment by HofmeisterAn** [comment]
> Exception is raised from context.Database.EnsureCreated, seems like example project doesn't call this method

It does too:

https://github.com/testcontainers/testcontainers-dotnet/blob/1c80fe80432873a625b2cde7ce52e99308d68b4e/examples/WeatherForecast/src/WeatherForecast.Contexts/WeatherDataReadOnlyContext.cs#L11

> I can reproduce it in https://github.com/dadyarri/FlexLabs.Upsert (branch support-oracle, IntegrationTests project).

If I have some time, I can take a look at it, but cannot promise it. Right now, I do not expect it to be an issue in Testcontainers.

**Comment by HofmeisterAn** [comment]
I reduced your `TestDbContext` to the bare minimum and only kept the `Book` entity and its `ID`. `EnsureCreatedAsync()` does not throw an exception anymore, and the table, including a test item, is successfully created.

    sh-4.4$ sqlplus system/oracle@localhost/XEPDB1

    SQL*Plus: Release 21.0.0.0.0 - Production on Thu Feb 8 17:58:53 2024
    Version 21.3.0.0.0

    Copyright (c) 1982, 2021, Oracle.  All rights reserved.

    Last Successful login time: Thu Feb 08 2024 17:58:24 +00:00

    Connected to:
    Oracle Database 21c Express Edition Release 21.0.0.0.0 - Production
    Version 21.3.0.0.0

    SQL> SELECT ID FROM "ORACLE"."Books";

    ID
    ----------
    1

    SQL> 

I think this issue is out of the scope of Testcontainers. Do you mind if we close it?

**Comment by dadyarri** [comment]
Okay, thanks
