### ISSUE TITLE
[Bug]: Problems with running dotnet integration tests with testcontainers on Gitlab CI/CD

### ISSUE THREAD

**Issue by MladenMircic** [testcontainers/testcontainers-dotnet#1197]
### Testcontainers version

3.8.0

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host arch

amd64

### .NET version

7.0.410

### Docker version

```shell
-
```

### Docker info

```shell
-
```

### What happened?

**Expected behavior**
Running dotnet xUnit integration tests are working correctly when run on local machine using MSSQL testcontainer. Same is expected when running them on Gitlab CI/CD using DinD service.

**Actual behavior**
Tests are failing because Ryuk initialization has stopped.

I have seen multiple issues reported on the same topic and I have tried almost all of the suggested solutions which include setting `TESTCONTAINERS_HOST_OVERRIDE: "host.docker.internal"` and `TESTCONTAINERS_HOST_OVERRIDE: "localhost"` and disabling Ryuk altogether.

Exception when I set `TESTCONTAINERS_HOST_OVERRIDE: "host.docker.internal"`:

```
Error Message:
   DotNet.Testcontainers.Containers.ResourceReaperException : Initialization has been cancelled.
  Stack Trace:
     at DotNet.Testcontainers.Containers.ResourceReaper.GetAndStartNewAsync(Guid sessionId, IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, IImage resourceReaperImage, IMount dockerSocket, ILogger logger, Boolean requiresPrivilegedMode, TimeSpan initTimeout, CancellationToken ct) in /_/src/Testcontainers/Containers/ResourceReaper.cs:line 245
   at DotNet.Testcontainers.Containers.ResourceReaper.GetAndStartNewAsync(Guid sessionId, IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, IImage resourceReaperImage, IMount dockerSocket, ILogger logger, Boolean requiresPrivilegedMode, TimeSpan initTimeout, CancellationToken ct) in /_/src/Testcontainers/Containers/ResourceReaper.cs:line 257
   at DotNet.Testcontainers.Containers.ResourceReaper.GetAndStartDefaultAsync(IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, ILogger logger, Boolean isWindowsEngineEnabled, CancellationToken ct) in /_/src/Testcontainers/Containers/ResourceReaper.cs:line 149
   at DotNet.Testcontainers.Clients.TestcontainersClient.RunAsync(IContainerConfiguration configuration, CancellationToken ct) in /_/src/Testcontainers/Clients/TestcontainersClient.cs:line 294
   at DotNet.Testcontainers.Containers.DockerContainer.UnsafeCreateAsync(CancellationToken ct) in /_/src/Testcontainers/Containers/DockerContainer.cs:line 424
   at DotNet.Testcontainers.Containers.DockerContainer.StartAsync(CancellationToken ct) in /_/src/Testcontainers/Containers/DockerContainer.cs:line 288
   at NBS.CaseRegistry.IntegrationTests.Abstractions.IntegrationTestWebAppFactory.InitializeAsync() in /builds/km-nbs-projects/case-registry/tests/NBS.CaseRegistry.IntegrationTests/Abstractions/IntegrationTestWebAppFactory.cs:line 57
  Failed NBS.CaseRegistry.IntegrationTests.Mails.CreateMailFromActTests.CreateMailFromAct_ShouldBeValid_WhenUsingGlobalCategory [1 ms]
```

Exception when I set `TESTCONTAINERS_HOST_OVERRIDE: "localhost"`:

```
[testcontainers.org 00:00:00.09] Connected to Docker:
  Host: tcp://docker:2375/
  Server Version: 26.1.4
  Kernel Version: 5.15.154+
  API Version: 1.45
  Operating System: Alpine Linux v3.20 (containerized)
  Total Memory: 7.77 GB
[testcontainers.org 00:00:00.12] Docker config "/root/.docker/config.json" not found
[testcontainers.org 00:00:00.12] Searching Docker registry credential in Auths
[testcontainers.org 00:00:00.12] Docker registry credential https://index.docker.io/v1/ not found
[testcontainers.org 00:00:01.38] Docker image testcontainers/ryuk:0.6.0 created
[testcontainers.org 00:00:01.57] Docker container 5af8e5e6281c created
[testcontainers.org 00:00:01.62] Start Docker container 5af8e5e6281c
[testcontainers.org 00:00:01.93] Wait for Docker container 5af8e5e6281c to complete readiness checks
[testcontainers.org 00:00:01.93] Docker container 5af8e5e6281c ready
[testcontainers.org 00:01:02.10] Stop Docker container 5af8e5e6281c
```

And then every test throws the same exception:

```
Docker.DotNet.DockerContainerNotFoundException : Docker API responded with status code=NotFound, response={"message":"No such container: 5af8e5e6281ccd84a10b1add6572269cf066feac2d24b744f1f3143a70c7946a"}
```

Exception when I disable Ryuk:

```
Microsoft.Data.SqlClient.SqlException : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server: Could not open a connection to SQL Server)
```

### Additional information

**Container initialization factory**

````csharp
public sealed class IntegrationTestWebAppFactory : WebApplicationFactory<Program>, IAsyncLifetime
{
    private readonly MsSqlContainer _dbContainer =
        new MsSqlBuilder()
            .Build();

    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        builder.ConfigureTestServices(services =>
        {
            services.RemoveAll(typeof(DbContextOptions<MyDbContext>));

            var sqlConnectionStringBuilder =
                new SqlConnectionStringBuilder(_dbContainer.GetConnectionString())
                {
                    TrustServerCertificate = true,
                    Encrypt = false,
                    MultiSubnetFailover = true
                };

            services.AddDbContext<MyDbContext>(options =>
            {
                options.UseSqlServer(
                    sqlConnectionStringBuilder.ConnectionString,
                    sqlServerOptions => sqlServerOptions.CommandTimeout(20));
            });
        });
    }

    public async Task InitializeAsync()
    {
        await _dbContainer.StartAsync();
    }

    public async new Task DisposeAsync()
    {
        await _dbContainer.StopAsync();
    }
}
````

I have also tried binding to port 1433 for MSSQL

```
private readonly MsSqlContainer _dbContainer =
        new MsSqlBuilder()
            .WithPortBinding(1433, true)
            .WithWaitStrategy(Wait.ForUnixContainer().UntilPortIsAvailable(1433))
            .Build();
```

I am absolutely sure that I have misconfigured something, but I can't quite figure it out. Any help would be highly appreciated!

**Comment by HofmeisterAn** [comment]
Phew, it has been a while since I configured GitLab CI/CD with Testcontainers. IIRC it is not necessary to set the `TESTCONTAINERS_HOST_OVERRIDE` environment variable. Can you please remove all the environment variable configurations and follow [this](https://dotnet.testcontainers.org/cicd/#gitlab-cicd) and/or [this](https://www.atomicjar.com/2023/01/running-testcontainers-tests-on-gitlab-ci/) approach (without the Java-specific steps) to configure the DinD service? If you still run into issues, please follow up with the error.

**Comment by MladenMircic** [comment]
Those guides were my first on the topic so I already tried with only defining docker host and disabling TLS. Once again I am getting the following error:

```
Microsoft.Data.SqlClient.SqlException : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server: Could not open a connection to SQL Server)
```

This is a job I defined for executing integration tests now:

```
integration_tests:
  image: mcr.microsoft.com/dotnet/sdk:7.0

  script:
    - 'dotnet test ./MySolution.sln'
    
  services:
  - name: docker:dind
    command: ["--tls=false"]

  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2

```

I failed to mention, I am also using Hangfire library for background tasks. This is what I get with this configuration now:

```
[testcontainers.org 00:00:00.09] Connected to Docker:
  Host: tcp://docker:2375/
  Server Version: 26.1.4
  Kernel Version: 5.15.154+
  API Version: 1.45
  Operating System: Alpine Linux v3.20 (containerized)
  Total Memory: 7.77 GB
[testcontainers.org 00:00:00.13] Docker config "/root/.docker/config.json" not found
[testcontainers.org 00:00:00.13] Searching Docker registry credential in Auths
[testcontainers.org 00:00:00.13] Docker registry credential https://index.docker.io/v1/ not found
[testcontainers.org 00:00:01.30] Docker image testcontainers/ryuk:0.6.0 created
[testcontainers.org 00:00:01.43] Docker container 330928778e2b created
[testcontainers.org 00:00:01.47] Start Docker container 330928778e2b
[testcontainers.org 00:00:01.81] Wait for Docker container 330928778e2b to complete readiness checks
[testcontainers.org 00:00:01.81] Docker container 330928778e2b ready
[testcontainers.org 00:00:01.82] Docker config "/root/.docker/config.json" not found
[testcontainers.org 00:00:01.82] Searching Docker registry credential in Auths
[testcontainers.org 00:00:01.82] Docker registry credential mcr.microsoft.com not found
[testcontainers.org 00:00:29.19] Docker image mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04 created
[testcontainers.org 00:00:31.14] Docker container a11d99e74d02 created
[testcontainers.org 00:00:31.15] Start Docker container a11d99e74d02
[testcontainers.org 00:00:31.39] Wait for Docker container a11d99e74d02 to complete readiness checks
[testcontainers.org 00:00:31.40] Execute "/bin/sh -c true && (grep -i ':0*599' /proc/net/tcp* || nc -vz -w 1 localhost 1433 || /bin/bash -c '</dev/tcp/localhost/1433')" at Docker container a11d99e74d02
[testcontainers.org 00:00:32.51] Execute "/bin/sh -c true && (grep -i ':0*599' /proc/net/tcp* || nc -vz -w 1 localhost 1433 || /bin/bash -c '</dev/tcp/localhost/1433')" at Docker container a11d99e74d02
[testcontainers.org 00:00:33.57] Execute "/bin/sh -c true && (grep -i ':0*599' /proc/net/tcp* || nc -vz -w 1 localhost 1433 || /bin/bash -c '</dev/tcp/localhost/1433')" at Docker container a11d99e74d02
[testcontainers.org 00:00:34.64] Execute "/bin/sh -c true && (grep -i ':0*599' /proc/net/tcp* || nc -vz -w 1 localhost 1433 || /bin/bash -c '</dev/tcp/localhost/1433')" at Docker container a11d99e74d02
[testcontainers.org 00:00:35.74] Execute "/bin/sh -c true && (grep -i ':0*599' /proc/net/tcp* || nc -vz -w 1 localhost 1433 || /bin/bash -c '</dev/tcp/localhost/1433')" at Docker container a11d99e74d02
[testcontainers.org 00:00:35.80] Docker container a11d99e74d02 ready
2024-06-13 06:41:49.246 +00:00 [ERR] [Hangfire.SqlServer.SqlServerStorage] Was unable to use the TryAutoDetectSchemaDependentOptions option due to an exception.
```

I don't know if it's causing the problem or it is affected by the problem.

**Comment by MladenMircic** [comment]
It was a problem connecting Hangfire library to the test environment. It is now fixed, thank you :)

**Comment by HofmeisterAn** [comment]
Ok, this looks much better. In the logs, you can see that Testcontainers can pull, run, and access [Ryuk](https://github.com/testcontainers/moby-ryuk), and at least pull and run MSSQL.

According to the logs, it appears that you have overwritten the default wait strategy. Please do not. Your chosen wait strategy may indicate readiness too early (the network port is available before the actual service in the container is running). Please use the default builder configuration.

IIRC it is necessary to remove more DI registered services. Please refer to this [guide](https://testcontainers.com/guides/testing-an-aspnet-core-web-app/) for further details.

These days, I prefer to provide the connection string via the application settings and not mess around with the DI registered services (see [Set Redis connection string](https://dotnet.testcontainers.org/examples/aspnet/#utilizing-webapplicationfactory)).
