### ISSUE TITLE
[Bug]: fail to pull quay.io/testcontainers/ryuk:0.2.3

### ISSUE THREAD

**Issue by newbe36524** [testcontainers/testcontainers-dotnet#1199]
### Testcontainers version

3.8.0

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host arch

x86

### .NET version

8.0.302

### Docker version

```shell
Client: Docker Engine - Community
 Version:           26.1.4
 API version:       1.45
 Go version:        go1.21.11
 Git commit:        5650f9b
 Built:             Wed Jun  5 11:28:57 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.1.4
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       de5c9cf
  Built:            Wed Jun  5 11:28:57 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.33
  GitCommit:        d2d58213f83a351ca8f528a95fbd145f5654e957
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client: Docker Engine - Community
 Version:    26.1.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 7
  Running: 4
  Paused: 0
  Stopped: 3
 Images: 14
 Server Version: 26.1.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d2d58213f83a351ca8f528a95fbd145f5654e957
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-35-generic
 Operating System: Ubuntu 24.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.07GiB
 Name: newbe36524-83al
 ID: b6132784-ad76-4e32-8a7b-98bfda70bafa
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
```

### What happened?

```C#
Docker.DotNet.DockerImageNotFoundException : Docker API responded with status code=NotFound, response={"message":"No such image: quay.io/testcontainers/ryuk:0.2.3"}

   at Docker.DotNet.ImageOperations.<>c.<.cctor>b__27_0(HttpStatusCode statusCode, String responseBody)
   at Docker.DotNet.DockerClient.HandleIfErrorResponseAsync(HttpStatusCode statusCode, HttpResponseMessage response, IEnumerable`1 handlers)
```

### Additional information

if I try to pull directly by `docker pull quay.io/testcontainers/ryuk:0.2.3`. it shows:
```shell
0.2.3: Pulling from testcontainers/ryuk
[DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of quay.io/testcontainers/ryuk:0.2.3 to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/

```

**Comment by HofmeisterAn** [comment]
What are you trying to achieve? Could you please share the code that run into this issue? The version (0.2.3) of Ryuk is outdated and not included in the recent Testcontainers [versions](https://github.com/testcontainers/testcontainers-dotnet/blob/56d3eabbe0d9486ee4e3438d15c305fed607afc7/src/Testcontainers/Containers/ResourceReaper.cs#L36). The versions we are using are hosted on [Docker Hub](https://hub.docker.com/r/testcontainers/ryuk) (0.7.0).

**Comment by newbe36524** [comment]
> What are you trying to achieve? Could you please share the code that run into this issue? The version (0.2.3) of Ryuk is outdated and not included in the recent Testcontainers [versions](https://github.com/testcontainers/testcontainers-dotnet/blob/56d3eabbe0d9486ee4e3438d15c305fed607afc7/src/Testcontainers/Containers/ResourceReaper.cs#L36). The versions we are using are hosted on [Docker Hub](https://hub.docker.com/r/testcontainers/ryuk) (0.7.0).

Thank you for your reply.
My bad, sorry, I should include package `Testcontainers.PostgreSql` but actually `TestContainers.Container.Database.PostgreSql`.

I will do some migration to Testcontainers.PostgreSql in my projects to fix it.
