### ISSUE TITLE
[Bug]: Cannot start MsSql container

### ISSUE THREAD

**Issue by smbecker** [testcontainers/testcontainers-dotnet#1271]
### Testcontainers version

3.10.0

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host arch

x86

### .NET version

8.0

### Docker version

```shell
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:40:59 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:40:59 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.22
  GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 12
  Running: 3
  Paused: 0
  Stopped: 9
 Images: 69
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-45-generic
 Operating System: Ubuntu 24.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 48
 Total Memory: 125.6GiB
 Name: pc-ubuntu
 ID: 2db0cb28-60b6-4481-8a18-92ebf4d44f4c
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### What happened?

I have a sample app using the following code:

```c#
using Testcontainers.MsSql;

await using var container = new MsSqlBuilder().Build();
await container.StartAsync();
Console.WriteLine(container.GetConnectionString());
```

This fails with the following stack trace:

```
Unhandled exception. Docker.DotNet.DockerApiException: Docker API responded with status code=Conflict, response={"message":"container b94feb834d643fd1460ac1c4baa5309c6d83058ef906d611edf8fe9b77e03d15 is not running"}

   at Docker.DotNet.DockerClient.HandleIfErrorResponseAsync(HttpStatusCode statusCode, HttpResponseMessage response, IEnumerable`1 handlers)
   at Docker.DotNet.DockerClient.MakeRequestAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
   at Docker.DotNet.ExecOperations.ExecCreateContainerAsync(String id, ContainerExecCreateParameters parameters, CancellationToken cancellationToken)
   at DotNet.Testcontainers.Clients.DockerContainerOperations.ExecAsync(String id, IList`1 command, CancellationToken ct) in /_/src/Testcontainers/Clients/DockerContainerOperations.cs:line 150
   at Testcontainers.MsSql.MsSqlBuilder.WaitUntil.UntilAsync(MsSqlContainer container) in /_/src/Testcontainers.MsSql/MsSqlBuilder.cs:line 146
   at DotNet.Testcontainers.Containers.DockerContainer.CheckReadinessAsync(WaitStrategy waitStrategy, CancellationToken ct) in /_/src/Testcontainers/Containers/DockerContainer.cs:line 534
   at DotNet.Testcontainers.Configurations.WaitStrategy.<>c__DisplayClass24_0.<<WaitUntilAsync>g__UntilAsync|0>d.MoveNext() in /_/src/Testcontainers/Configurations/WaitStrategies/WaitStrategy.cs:line 184
--- End of stack trace from previous location ---
   at DotNet.Testcontainers.Configurations.WaitStrategy.WaitUntilAsync(Func`1 wait, TimeSpan interval, TimeSpan timeout, Int32 retries, CancellationToken ct) in /_/src/Testcontainers/Configurations/WaitStrategies/WaitStrategy.cs:line 213
   at DotNet.Testcontainers.Containers.DockerContainer.CheckReadinessAsync(IEnumerable`1 waitStrategies, CancellationToken ct) in /_/src/Testcontainers/Containers/DockerContainer.cs:line 552
   at DotNet.Testcontainers.Containers.DockerContainer.UnsafeStartAsync(CancellationToken ct) in /_/src/Testcontainers/Containers/DockerContainer.cs:line 479
   at DotNet.Testcontainers.Containers.DockerContainer.StartAsync(CancellationToken ct) in /_/src/Testcontainers/Containers/DockerContainer.cs:line 282
   at Program.<Main>$(String[] args) in /home/user/dev/spikes/TestContainerSqlServer/TestContainerSqlServer/Program.cs:line 4
   at Program.<Main>$(String[] args) in /home/user/dev/spikes/TestContainerSqlServer/TestContainerSqlServer/Program.cs:line 5
   at Program.<Main>(String[] args)
```

### Relevant log output

```shell
[testcontainers.org 00:00:00.38] Connected to Docker:
  Host: unix:///var/run/docker.sock
  Server Version: 27.3.1
  Kernel Version: 6.8.0-45-generic
  API Version: 1.47
  Operating System: Ubuntu 24.04.1 LTS
  Total Memory: 125.63 GB

[testcontainers.org 00:00:00.73] Docker container a898790633d5 created
[testcontainers.org 00:00:00.88] Start Docker container a898790633d5
[testcontainers.org 00:00:01.31] Wait for Docker container a898790633d5 to complete readiness checks
[testcontainers.org 00:00:01.34] Docker container a898790633d5 ready
[testcontainers.org 00:00:01.39] Docker container b94feb834d64 created
[testcontainers.org 00:00:01.44] Start Docker container b94feb834d64
[testcontainers.org 00:00:01.87] Wait for Docker container b94feb834d64 to complete readiness checks
[testcontainers.org 00:00:02.06] Execute "/bin/sh -c find /opt/mssql-tools*/bin/sqlcmd -type f -print -quit" at Docker container b94feb834d64
[testcontainers.org 00:00:02.22] Execute "/opt/mssql-tools/bin/sqlcmd -C -Q SELECT 1;" at Docker container b94feb834d64
[testcontainers.org 00:00:10.67] Execute "/opt/mssql-tools/bin/sqlcmd -C -Q SELECT 1;" at Docker container b94feb834d64
[testcontainers.org 00:00:11.35] Delete Docker container b94feb834d64
```

**Comment by smbecker** [comment]
I was able to capture the logs of the container before it was deleted:

```
SQL Server 2019 will run as non-root by default.
This container is running as user mssql.
To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
2024-09-23 15:06:45.91 Server      Setup step is copying system data file 'C:\templatedata\master.mdf' to '/var/opt/mssql/data/master.mdf'.
2024-09-23 15:06:45.93 Server      Did not find an existing master data file /var/opt/mssql/data/master.mdf, copying the missing default master and other system database files. If you have moved the database location, but not moved the database files, startup may fail. To repair: shutdown SQL Server, move the master database to configured location, and restart.
2024-09-23 15:06:45.93 Server      Setup step is copying system data file 'C:\templatedata\mastlog.ldf' to '/var/opt/mssql/data/mastlog.ldf'.
2024-09-23 15:06:45.94 Server      Setup step is copying system data file 'C:\templatedata\model.mdf' to '/var/opt/mssql/data/model.mdf'.
2024-09-23 15:06:45.95 Server      Setup step is copying system data file 'C:\templatedata\modellog.ldf' to '/var/opt/mssql/data/modellog.ldf'.
2024-09-23 15:06:45.96 Server      Setup step is copying system data file 'C:\templatedata\msdbdata.mdf' to '/var/opt/mssql/data/msdbdata.mdf'.
2024-09-23 15:06:45.98 Server      Setup step is copying system data file 'C:\templatedata\msdblog.ldf' to '/var/opt/mssql/data/msdblog.ldf'.
2024-09-23 15:06:45.98 Server      Setup step is FORCE copying system data file 'C:\templatedata\model_replicatedmaster.mdf' to '/var/opt/mssql/data/model_replicatedmaster.mdf'.
2024-09-23 15:06:45.99 Server      Setup step is FORCE copying system data file 'C:\templatedata\model_replicatedmaster.ldf' to '/var/opt/mssql/data/model_replicatedmaster.ldf'.
2024-09-23 15:06:45.99 Server      Setup step is FORCE copying system data file 'C:\templatedata\model_msdbdata.mdf' to '/var/opt/mssql/data/model_msdbdata.mdf'.
2024-09-23 15:06:46.01 Server      Setup step is FORCE copying system data file 'C:\templatedata\model_msdblog.ldf' to '/var/opt/mssql/data/model_msdblog.ldf'.
2024-09-23 15:06:46.04 Server      Microsoft SQL Server 2019 (RTM-CU18) (KB5017593) - 15.0.4261.1 (X64)
	Sep 12 2022 15:07:06
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 20.04.5 LTS) <X64>
2024-09-23 15:06:46.04 Server      UTC adjustment: 0:00
2024-09-23 15:06:46.04 Server      (c) Microsoft Corporation.
2024-09-23 15:06:46.04 Server      All rights reserved.
2024-09-23 15:06:46.04 Server      Server process ID is 412.
2024-09-23 15:06:46.04 Server      Logging SQL Server messages in file '/var/opt/mssql/log/errorlog'.
2024-09-23 15:06:46.04 Server      Registry startup parameters:
	 -d /var/opt/mssql/data/master.mdf
	 -l /var/opt/mssql/data/mastlog.ldf
	 -e /var/opt/mssql/log/errorlog
2024-09-23 15:06:46.05 Server      SQL Server detected 1 sockets with 24 cores per socket and 48 logical processors per socket, 48 total logical processors; using 48 logical processors based on SQL Server licensing. This is an informational message; no user action is required.
2024-09-23 15:06:46.05 Server      SQL Server is starting at normal priority base (=7). This is an informational message only. No user action is required.
2024-09-23 15:06:46.05 Server      Detected 102912 MB of RAM. This is an informational message; no user action is required.
2024-09-23 15:06:46.05 Server      Using conventional memory in the memory manager.
2024-09-23 15:06:46.05 Server      Page exclusion bitmap is enabled.
2024-09-23 15:06:46.13 Server      Buffer pool extension is not supported on Linux platform.
2024-09-23 15:06:46.13 Server      Buffer Pool: Allocating 16777216 bytes for 8952043 hashPages.
2024-09-23 15:06:46.27 Server      Automatic soft-NUMA was enabled because SQL Server has detected hardware NUMA nodes with greater than 8 physical cores.
2024-09-23 15:06:46.32 Server      Buffer pool extension is already disabled. No action is necessary.
2024-09-23 15:06:46.46 Server      Successfully initialized the TLS configuration. Allowed TLS protocol versions are ['1.0 1.1 1.2']. Allowed TLS ciphers are ['ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:!DHE-RSA-AES256-GCM-SHA384:!DHE-RSA-AES128-GCM-SHA256:!DHE-RSA-AES256-SHA:!DHE-RSA-AES128-SHA'].
2024-09-23 15:06:46.47 Server      Query Store settings initialized with enabled = 1,
2024-09-23 15:06:46.49 Server      The maximum number of dedicated administrator connections for this instance is '1'
2024-09-23 15:06:46.51 Server      Node configuration: node 0: CPU mask: 0x0000000000555555:0 Active CPU mask: 0x0000000000555555:0. This message provides a description of the NUMA configuration for this computer. This is an informational message only. No user action is required.
2024-09-23 15:06:46.51 Server      Node configuration: node 1: CPU mask: 0x0000555555000000:0 Active CPU mask: 0x0000555555000000:0. This message provides a description of the NUMA configuration for this computer. This is an informational message only. No user action is required.
2024-09-23 15:06:46.51 Server      Node configuration: node 2: CPU mask: 0x0000000000aaaaaa:0 Active CPU mask: 0x0000000000aaaaaa:0. This message provides a description of the NUMA configuration for this computer. This is an informational message only. No user action is required.
2024-09-23 15:06:46.51 Server      Node configuration: node 3: CPU mask: 0x0000aaaaaa000000:0 Active CPU mask: 0x0000aaaaaa000000:0. This message provides a description of the NUMA configuration for this computer. This is an informational message only. No user action is required.
2024-09-23 15:06:46.78 Server      Using dynamic lock allocation.  Initial allocation of 2500 Lock blocks and 5000 Lock Owner blocks per node.  This is an informational message only.  No user action is required.
2024-09-23 15:06:46.78 Server      Lock partitioning is enabled.  This is an informational message only. No user action is required.
2024-09-23 15:06:46.80 Server      In-Memory OLTP initialized on standard machine.
2024-09-23 15:06:46.84 Server      [INFO] Created Extended Events session 'hkenginexesession'
2024-09-23 15:06:46.84 Server      Database Instant File Initialization: enabled. For security and performance considerations see the topic 'Database Instant File Initialization' in SQL Server Books Online. This is an informational message only. No user action is required.
ForceFlush is enabled for this instance.
2024-09-23 15:06:46.84 Server      Total Log Writer threads: 6. This is an informational message; no user action is required.
2024-09-23 15:06:46.85 Server      clwb is selected for pmem flush operation.
2024-09-23 15:06:46.85 Server      Software Usage Metrics is disabled.
2024-09-23 15:06:46.86 spid13s     [1]. Feature Status: PVS: 0. CTR: 0. ConcurrentPFSUpdate: 1.
2024-09-23 15:06:46.86 spid13s     Starting up database 'master'.
ForceFlush feature is enabled for log durability.
2024-09-23 15:06:46.91 spid13s     The tail of the log for database master is being rewritten to match the new sector size of 4096 bytes.  1536 bytes at offset 412160 in file /var/opt/mssql/data/mastlog.ldf will be written.
2024-09-23 15:06:46.94 Server      CLR version v4.0.30319 loaded.
2024-09-23 15:06:46.95 spid13s     Converting database 'master' from version 897 to the current version 904.
2024-09-23 15:06:46.95 spid13s     Database 'master' running the upgrade step from version 897 to version 898.
2024-09-23 15:06:46.97 spid13s     Database 'master' running the upgrade step from version 898 to version 899.
This program has encountered a fatal error and cannot continue running at Mon Sep 23 15:06:46 2024
The following diagnostic information is available:

         Reason: 0x00000001
         Signal: SIGABRT - Aborted (6)
          Stack:
                 IP               Function
                 ---------------- --------------------------------------
                 000061b3049f8bec <unknown>
                 000061b3049f8632 <unknown>
                 000061b3049f7c41 <unknown>
                 00007cccdb09b090 killpg+0x40
                 00007cccdb09b00b gsignal+0xcb
                 00007cccdb07a859 abort+0x12b
                 000061b3049812a2 <unknown>
        Process: 9 - sqlservr
         Thread: 176 (application thread 0x2b8)
    Instance Id: 618a4c15-06a1-44c9-8fcb-bac4ac4d7663
       Crash Id: 4b79c54d-5646-44b5-81d8-23fc30151f00
    Build stamp: f708684a2cfcb51177273c54f975ed8c62029cbc89aa962bf7d6b956f01a0c27
   Distribution: Ubuntu 20.04.5 LTS
     Processors: 48
   Total Memory: 134889705472 bytes
      Timestamp: Mon Sep 23 15:06:46 2024
     Last errno: 2
Last errno text: No such file or directory
Capturing a dump of 9
Successfully captured dump: /var/opt/mssql/log/core.sqlservr.9_23_2024_15_6_47.9
Executing: /opt/mssql/bin/handle-crash.sh with parameters
     handle-crash.sh
     /opt/mssql/bin/sqlservr
     9
     /opt/mssql/bin
     /var/opt/mssql/log/

     618a4c15-06a1-44c9-8fcb-bac4ac4d7663
     4b79c54d-5646-44b5-81d8-23fc30151f00

     /var/opt/mssql/log/core.sqlservr.9_23_2024_15_6_47.9

Ubuntu 20.04.5 LTS
Capturing core dump and information to /var/opt/mssql/log...
/bin/cat: /proc/9/maps: Permission denied
```

**Comment by smbecker** [comment]
I am going to close this as I don't believe the issue is related to Testcontainers. The logs above led me to [this issue](https://github.com/microsoft/mssql-docker/issues/868#issuecomment-1918092133) where it seems to be related to running the 6.7 kernel.

**Comment by smbecker** [comment]
For anyone else encountering this issue, using `.WithImage("mcr.microsoft.com/mssql/server:2022-latest")` seems to fix the issue.
