### ISSUE TITLE
Create container from local image

### ISSUE THREAD

**Issue by paulvanbladel** [testcontainers/testcontainers-dotnet#215]
I created with docker a local image subsystem1image
```
$ docker image ls
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
subsystem1image                        latest              5c80ff39d55f        3 hours ago         208MB
...
```
When I try to consume the image with dotnet-testcontainers as follows, it fails:
```
var testcontainersBuilder = new TestcontainersBuilder<TestcontainersContainer>()
             
              .WithImage("subsystem1image")
              .WithName("subsystem1")
              .WithPortBinding(8081, 80)
              .WithWaitStrategy(Wait.UntilPortsAreAvailable(80));

            using (var testcontainer = testcontainersBuilder.Build())
            {
                await testcontainer.StartAsync();
                var request = WebRequest.Create("http://localhost:8081/WeatherForecast");
                var response = request.GetResponse();
...
```
with error:
```
Error Message:
   Docker.DotNet.DockerApiException : Docker API responded with status code=NotFound, response={"message":"pull access denied for subsystem1image, repository does not exist or may require 'docker login': 
denied: requested access to the resource is denied"}

  Stack Trace:
     at Docker.DotNet.DockerClient.HandleIfErrorResponseAsync(HttpStatusCode statusCode, HttpResponseMessage response, IEnumerable`1 handlers)
   at Docker.DotNet.DockerClient.MakeRequestForStreamAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
   at Docker.DotNet.Models.StreamUtil.MonitorStreamForMessagesAsync[T](Task`1 streamTask, DockerClient client, CancellationToken cancel, IProgress`1 progress)
   at DotNet.Testcontainers.Client.TestcontainersClient.RunAsync(TestcontainersConfiguration config, CancellationToken ct)
   at DotNet.Testcontainers.Containers.Modules.TestcontainersContainer.Create()
   at DotNet.Testcontainers.Containers.Modules.TestcontainersContainer.StartAsync()
   at OutboxPattern.DockerIntegrationTests.UnitTest1.MyOwnContainer() in D:\tfs\OutboxPattern\tests\OutboxPattern.DockerIntegrationTests\UnitTest1.cs:line 57
--- End of stack trace from previous location where exception was thrown ---

```

**Comment by HofmeisterAn** [comment]
I think you already created this issue (#183). Which version are you using? It should be fixed within 1.1.0 (https://github.com/HofmeisterAn/dotnet-testcontainers/issues/183#issuecomment-573405013). You should definitely update to the latest version.
