### ISSUE TITLE
"System.IO.IOException : Unable to read data from the transport connection: Broken pipe" when using ImageFromDockerfileBuilder to build image

### ISSUE THREAD

**Issue by sadunaresh** [testcontainers/testcontainers-dotnet#323]
I have this in my docker file

```
`FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base

WORKDIR /app

COPY . .

ENTRYPOINT ["dotnet", "httpapi.dll"]`
```

and trying to do below in  my code :

````
var imageBuilder = new ImageFromDockerfileBuilder();

            imageBuilder.WithDockerfileDirectory(Environment.CurrentDirectory)
            .WithName(testImageName)
            .WithDeleteIfExists(false);

            try
            {
                var image = await imageBuilder.Build();

            }
            catch (System.Exception ex)
            {
                throw;
            }
````

to see below exception:
```

`[xUnit.net 00:02:04.40]       System.Net.Http.HttpRequestException : The requested failed, see inner exception for details.
[xUnit.net 00:02:04.41]       ---- System.Net.Http.HttpRequestException : Error while copying content to a stream.
[xUnit.net 00:02:04.41]       -------- System.IO.IOException : Unable to read data from the transport connection: Broken pipe.
[xUnit.net 00:02:04.41]       ------------ System.Net.Sockets.SocketException : Broken pipe
[xUnit.net 00:02:04.41]       Stack Trace:
[xUnit.net 00:02:04.42]            at Microsoft.Net.Http.Client.HttpConnection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[xUnit.net 00:02:04.42]            at Microsoft.Net.Http.Client.ManagedHandler.ProcessRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[xUnit.net 00:02:04.42]            at Microsoft.Net.Http.Client.ManagedHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[xUnit.net 00:02:04.42]            at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
[xUnit.net 00:02:04.42]            at Docker.DotNet.DockerClient.PrivateMakeRequestAsync(TimeSpan timeout, HttpCompletionOption completionOption, HttpMethod method, String path, IQueryString queryString, IDictionary`2 headers, IRequestContent data, CancellationToken cancellationToken)
[xUnit.net 00:02:04.42]            at Docker.DotNet.DockerClient.MakeRequestForStreamAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
[xUnit.net 00:02:04.42]            at DotNet.Testcontainers.Clients.DockerImageOperations.BuildAsync(IImageFromDockerfileConfiguration config, CancellationToken ct)
[xUnit.net 00:02:04.42]         /home/Code/service/qatests/integrationtests/integrationWithServiceContainer.cs(34,0): at integrationtests.IntegrationWithServiceContainer.ShouldFailToStart_WhenRedisUnavailable()
[xUnit.net 00:02:04.42]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:02:04.42]         ----- Inner Stack Trace -----
[xUnit.net 00:02:04.42]            at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask)
[xUnit.net 00:02:04.42]            at Microsoft.Net.Http.Client.HttpConnection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[xUnit.net 00:02:04.42]         ----- Inner Stack Trace -----
[xUnit.net 00:02:04.42]            at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
[xUnit.net 00:02:04.42]            at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
[xUnit.net 00:02:04.42]            at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
[xUnit.net 00:02:04.42]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:02:04.42]            at System.IO.Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
[xUnit.net 00:02:04.42]            at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask)
[xUnit.net 00:02:04.42]         ----- Inner Stack Trace -----`
```

please could you help me find what is going wrong here

**Comment by HofmeisterAn** [comment]
I'm currently out of town and won't be able to take a closer look at it until next week.

But I’m pretty sure I already found what you’re doing wrong. You’re using the builder pattern in a wrong way.

You create an instance of `ImageFromDockerfileBuilder` but never assign the new configuration to that instance. Keep in mind, the builder pattern always returns a **new** configured instance.

Use instead:

```csharp
var imageBuilder = new ImageFromDockerfileBuilder()
  .WithDockerfileDirectory(Environment.CurrentDirectory)
  .WithName(testImageName)
  .WithDeleteIfExists(false);
```

**Comment by sadunaresh** [comment]
@HofmeisterAn - Thank you, for looking into this. 

changed the code as suggested, but didn't resolve the issue.

On closer look, the problem was with below line in my dockerfile

COPY . .

the above command is trying to copy the test project dll(which runs above code) is being used by the xunit runner process.

When I moved the files required to build the image to a separate folder and modified the dockerfile appropriately, the image built successfully.

so this isn't an issue with the library.

thank you, again for your support.
