### ISSUE TITLE
Bitbucket CI Pipeline for TestContainers

### ISSUE THREAD

**Issue by pixime** [testcontainers/testcontainers-dotnet#359]
Hello,

I have read the previous issue https://github.com/HofmeisterAn/dotnet-testcontainers/issues/333 regarding integration of TestContainer in CI Pipeline. I have a similar problem.

I use Bitbucket to run tests, here is my pipeline:

```
image: mcr.microsoft.com/dotnet/core/sdk:3.1

options:
  docker: true

pipelines:
  default:
    - step:
        script:
          - docker ps
          - dotnet restore
          - dotnet test ModelRunnerSvc.Tests
        services:
          - docker
        caches:
          - docker
```

Notice that I run `docker ps` in order two check if docker is available and it seems Ok. 
When I run the pipeline, here is the result:

```
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:01.42]     ModelRunnerSvc.Tests.JobControllerTest.SubmitModel_GetJob_WhenCalled_ReturnsJob [FAIL]
[xUnit.net 00:00:01.46]     ModelRunnerSvc.Tests.JobControllerTest.Submit3Models_GetJobs_WhenCalled_Returns3Jobs [FAIL]
[xUnit.net 00:00:01.53]     ModelRunnerSvc.Tests.JobControllerTest.GetJob_WhenCalled_ReturnsEmptyResult [FAIL]
  X ModelRunnerSvc.Tests.JobControllerTest.SubmitModel_GetJob_WhenCalled_ReturnsJob [479ms]
  Error Message:
   System.Net.Http.HttpRequestException : Connection failed
---- System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Cannot assign requested address /var/run/docker.sock
  Stack Trace:
     at Microsoft.Net.Http.Client.ManagedHandler.ProcessRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Net.Http.Client.ManagedHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Docker.DotNet.DockerClient.PrivateMakeRequestAsync(TimeSpan timeout, HttpCompletionOption completionOption, HttpMethod method, String path, IQueryString queryString, IDictionary`2 headers, IRequestContent data, CancellationToken cancellationToken)
   at Docker.DotNet.DockerClient.PrivateMakeRequestAsync(TimeSpan timeout, HttpCompletionOption completionOption, HttpMethod method, String path, IQueryString queryString, IDictionary`2 headers, IRequestContent data, CancellationToken cancellationToken)
   at Docker.DotNet.DockerClient.MakeRequestAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
   at Docker.DotNet.ImageOperations.ListImagesAsync(ImagesListParameters parameters, CancellationToken cancellationToken)
   at DotNet.Testcontainers.Clients.DockerImageOperations.ByPropertyAsync(String property, String value, CancellationToken ct)
   at DotNet.Testcontainers.Clients.DockerImageOperations.ExistsWithNameAsync(String name, CancellationToken ct)
   at DotNet.Testcontainers.Clients.TestcontainersClient.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
   at DotNet.Testcontainers.Containers.Modules.TestcontainersContainer.Create(CancellationToken ct)
   at DotNet.Testcontainers.Containers.Modules.TestcontainersContainer.StartAsync(CancellationToken ct)
   at ModelRunnerSvc.Tests.JobControllerTest.SubmitModel_GetJob_WhenCalled_ReturnsJob() in /opt/atlassian/pipelines/agent/build/ModelRunnerSvc.Tests/JobControllerTest.cs:line 96
   at ModelRunnerSvc.Tests.JobControllerTest.SubmitModel_GetJob_WhenCalled_ReturnsJob() in /opt/atlassian/pipelines/agent/build/ModelRunnerSvc.Tests/JobControllerTest.cs:line 111

```

My test code use TestContainer, which use DotNet.Docker, which use Net.Http.Client and it fails when I try to execute:
`await testContainer.StartAsync();`
I suppose that the instructions given to Docker are behind...

In the previous post, you suggested:
_In your first error, you are using docker socket -> /var/run/docker.sock , for this sample, you need to mount socket file._

I don't understand what you meant. Do you have a detailed suggestion to fix this behavior ?

**Comment by HofmeisterAn** [comment]
I'm not familiar with the Atlassian Bitbucket pipeline, but I guess your example code will start a docker container based on `mcr.microsoft.com/dotnet/core/sdk:3.1` and execute each script task.

Each script task is executed **inside** the container. It looks like the container does not provide the default Docker daemon endpoint for Unix  that Docker or Testcontainers usually use (`/var/run/docker.sock`). Unfortunately, the Atlassian Support [documentation](https://support.atlassian.com/bitbucket-cloud/docs/run-docker-commands-in-bitbucket-pipelines/#How-it-works) does not contain any further information.

It's common to expose `/var/run/docker.sock` to your container by mounting it. Or you configure an external Docker daemon and access it with `WithDockerEndpoint`.

What Docker daemon does your container use?

**Comment by pixime** [comment]
Thanks for your help. I will google this case and post the issue to bitbucket. Hope I will find a workaround.

**Comment by HofmeisterAn** [comment]
I'll do some tests with my Bitbucket account too, when I have some time left.

**Comment by HofmeisterAn** [comment]
@pixime If you take a closer look into the output of `docker context ls` or `echo $DOCKER_HOST`, you will notice that Atlassian Bitbucket exposes the daemon to `tcp://localhost:2375` (in my pipeline). This is not the default endpoint. However, you can set the endpoint with `WithDockerEndpoint`. You should change your code to something like this:

```csharp
var dockerEndpoint = Environment.GetEnvironmentVariable("DOCKER_HOST");
_container = new TestcontainersBuilder<TestcontainersContainer>()
  .WithDockerEndpoint(dockerEndpoint)
  .WithImage("alpine")
  .Build();
```

Notice `.WithDockerEndpoint(dockerEndpoint)` in the example above.

**Comment by HofmeisterAn** [comment]
I'll close this. If you need any further help don't hesitate to comment.
