### ISSUE TITLE
Docker.DotNet.DockerImageNotFoundException

### ISSUE THREAD

**Issue by Pastafarian** [testcontainers/testcontainers-dotnet#522]
I'm getting the same issue that was mentioned previously in the following issue. 

https://github.com/testcontainers/testcontainers-dotnet/issues/424

Everything works fine locally but as soon as I try running my integration tests on azure dev ops I get the following error. 

Docker.DotNet.DockerImageNotFoundException : Docker API responded with status code=NotFound, response={"message":"No such image: postgres:14.4"}

The full error log:

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:08.51]     DevBlog.Api.IntTests.Controllers.ContactControllerTests.GivenInvalidContact_WhenExecuted_ThenErrorReturned [FAIL]
[xUnit.net 00:00:08.53]     DevBlog.Api.IntTests.Controllers.PostControllerTests.Given10PostsExist_WhenIndexCalled_Then10PreviewsReturned [FAIL]
[xUnit.net 00:00:08.54]     DevBlog.Api.IntTests.Controllers.ContactControllerTests.GivenValidContact_WhenExecuted_ThenOkResponseReturned [FAIL]
[xUnit.net 00:00:08.54]     [Test Class Cleanup Failure (DevBlog.Api.IntTests.Controllers.ContactControllerTests)] System.InvalidOperationException
[xUnit.net 00:00:08.54]     [Test Class Cleanup Failure (DevBlog.Api.IntTests.Controllers.PostControllerTests)] System.InvalidOperationException
  Failed DevBlog.Api.IntTests.Controllers.ContactControllerTests.GivenInvalidContact_WhenExecuted_ThenErrorReturned [1 ms]
  Error Message:
   Docker.DotNet.DockerImageNotFoundException : Docker API responded with status code=NotFound, response={"message":"No such image: postgres:14.4"}

  Stack Trace:
     at Docker.DotNet.ContainerOperations.<>c.<.cctor>b__30_1(HttpStatusCode statusCode, String responseBody)
   at Docker.DotNet.DockerClient.HandleIfErrorResponseAsync(HttpStatusCode statusCode, HttpResponseMessage response, IEnumerable`1 handlers)
   at Docker.DotNet.DockerClient.MakeRequestAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
   at Docker.DotNet.ContainerOperations.CreateContainerAsync(CreateContainerParameters parameters, CancellationToken cancellationToken)
   at DotNet.Testcontainers.Clients.DockerContainerOperations.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
   at DotNet.Testcontainers.Clients.TestcontainersClient.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
   at DotNet.Testcontainers.Containers.TestcontainersContainer.Create(CancellationToken ct)
   at DotNet.Testcontainers.Containers.TestcontainersContainer.StartAsync(CancellationToken ct)
   at DevBlog.Api.IntTests.Framework.ApiWebApplicationFactory.InitializeAsync() in D:\a\1\s\server\Tests\DevBlog.Api.IntTests\Framework\ApiWebApplicationFactory.cs:line 63
  Failed DevBlog.Api.IntTests.Controllers.PostControllerTests.Given10PostsExist_WhenIndexCalled_Then10PreviewsReturned [1 ms]
  Error Message:
   Docker.DotNet.DockerImageNotFoundException : Docker API responded with status code=NotFound, response={"message":"No such image: postgres:14.4"}
```

I tried using the long form of the WithImage and including docker.io along with using WithRegistryAuthentication with my docker hub account credentials but I'm still getting the same issue. 

Do you have any idea what could be going on? 

```
    private readonly TestcontainerDatabase testcontainers = new TestcontainersBuilder<PostgreSqlTestcontainer>()
        .WithDatabase(new PostgreSqlTestcontainerConfiguration
        {
            Database = "db",
            Username = "postgres",
            Password = "postgres"
        })
        .WithImage("docker.io/postgres:14.4")
        .WithRegistryAuthentication("https://hub.docker.com/", "fooobarbaz", "xxxxxxx")
        .Build();
```

**Comment by HofmeisterAn** [comment]
> [...] along with using WithRegistryAuthentication with my docker hub account credentials but I'm still getting the same issue.

`WithRegistryAuthentication` is obsolete and shouldn't be not necessary anymore.

Do you use a private build agent? What's your Docker engine? It looks like you're running on Windows. I don't think a `postgres` image is available for Windows.

Do you use a private Docker registry or run proxy? What does `docker pull postgres` say?

**Comment by Pastafarian** [comment]
Thanks for the quick response @HofmeisterAn. 

It was the fact I was running it on a windows box that caused the issue. 

By switching out the image from windows-latest to ubuntu-20.04 I resolved the issue. 

```
  pool:
      vmImage: 'ubuntu-20.04'
```
