### ISSUE TITLE
Creating Database Container throws DockerApiException

### ISSUE THREAD

**Issue by m0ddixx** [testcontainers/testcontainers-dotnet#585]
**Describe the bug**
When creating a Database Container (e.g. NpgSql or MsSql) throws a DockerApiException with the following Response:
`code=BadRequest, response={"message":"invalid filter 'reference'"}` 

Container Registration:
```csharp
private readonly PostgreSqlTestcontainer _database = new TestcontainersBuilder<PostgreSqlTestcontainer>()
        .WithDatabase(new PostgreSqlTestcontainerConfiguration
        {
            Database = "test",
            Username = "user",
            Password = "password",
        })
        .Build();
```

<details>
  <summary>Stacktrace</summary>
  
```
    Index Failed: Docker.DotNet.DockerApiException: Docker API responded with status code=BadRequest, response={"message":"invalid filter 'reference'"}
Docker.DotNet.DockerApiException
Docker API responded with status code=BadRequest, response={"message":"invalid filter 'reference'"}

   at Docker.DotNet.DockerClient.HandleIfErrorResponseAsync(HttpStatusCode statusCode, HttpResponseMessage response, IEnumerable`1 handlers)
   at Docker.DotNet.DockerClient.MakeRequestAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
   at Docker.DotNet.ImageOperations.ListImagesAsync(ImagesListParameters parameters, CancellationToken cancellationToken)
   at DotNet.Testcontainers.Clients.DockerImageOperations.ByPropertyAsync(String property, String value, CancellationToken ct)
   at DotNet.Testcontainers.Clients.DockerImageOperations.ExistsWithNameAsync(String name, CancellationToken ct)
   at DotNet.Testcontainers.Clients.TestcontainersClient.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
   at DotNet.Testcontainers.Containers.TestcontainersContainer.Create(CancellationToken ct)
   at DotNet.Testcontainers.Containers.TestcontainersContainer.StartAsync(CancellationToken ct)
   at DotNet.Testcontainers.Containers.ResourceReaper.GetAndStartNewAsync(Guid sessionId, IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, String ryukImage, TimeSpan initTimeout, CancellationToken ct)
   at DotNet.Testcontainers.Containers.ResourceReaper.GetAndStartNewAsync(Guid sessionId, IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, String ryukImage, TimeSpan initTimeout, CancellationToken ct)
   at DotNet.Testcontainers.Containers.ResourceReaper.GetAndStartDefaultAsync(IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, CancellationToken ct)
   at DotNet.Testcontainers.Clients.TestcontainersClient.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
   at DotNet.Testcontainers.Containers.TestcontainersContainer.Create(CancellationToken ct)
   at DotNet.Testcontainers.Containers.TestcontainersContainer.StartAsync(CancellationToken ct)
   at Tests.Backoffice.Xunit.IAsyncLifetime.InitializeAsync()
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90


```
</details>

If it helps, the DockerImageOperation part tries to assemble a reference Filter with the image tag `ghcr.io/psanetra/ryuk:2021.12.20`

**Additional Information**
Testcontainers 2.1.0
Docker Desktop 4.12.0 (85629)
Windows 10 19044.1889
Running on WSL2 Engine

**Comment by HofmeisterAn** [comment]
I cannot reproduce it with Docker Desktop for Mac. I'll have access to a Windows machine sometimes next week. Then I can double-check if version 4.12.0 breaks something.

Can you disable the resource reaper and test if it is able to pull the database images (`TestcontainersSettings.ResourceReaperEnabled = false`)?

**Comment by m0ddixx** [comment]
Thank you for your Response.
I put that in the ModuleInitializer annotated Block of xUnit, but now it fails with `postgres:11.14`

**Comment by m0ddixx** [comment]
I tried to debug further to see what the outcoming request URI is, which the Docker Engine API receives.
`http://localhost:2375/images/json?all=1&filters={%22reference%22:{%22postgres:11.14%22:true}}`
This looks pretty fine to me and also trying to use other API versions like v1.12 or v1.40 doesnt seem to change the error message.
This could be a parsing error in Docker Desktop, since the specification for the /images/json endpoint hasn't changed since.

**Comment by m0ddixx** [comment]
I have opened an issue over at moby/moby/issues/44161
I suggest we'll wait for them to respond, since this seems to be an issue with docker engine.

**Comment by m0ddixx** [comment]
So it seems, that the containerd integration on Windows is the issue. I think i can close this as resolved.

**Comment by HofmeisterAn** [comment]
Thanks for keeping me up to date.
