### ISSUE TITLE
DotNet.Testcontainers.Containers.ResourceReaperException : Initialization has been cancelled.

### ISSUE THREAD

**Issue by raman-kazhadub** [testcontainers/testcontainers-dotnet#620]
I just created 8 x PostgreSqlTest from your examples. And some times (some times ok) some tests are failed because of
 ```
DotNet.Testcontainers.Containers.ResourceReaperException.
DotNet.Testcontainers.Containers.ResourceReaperException : Initialization has been cancelled.
   at DotNet.Testcontainers.Containers.ResourceReaper.GetAndStartNewAsync(Guid sessionId, IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, String ryukImage, TimeSpan initTimeout, CancellationToken ct)
   at DotNet.Testcontainers.Containers.ResourceReaper.GetAndStartNewAsync(Guid sessionId, IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, String ryukImage, TimeSpan initTimeout, CancellationToken ct)
   at DotNet.Testcontainers.Containers.ResourceReaper.GetAndStartDefaultAsync(IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, CancellationToken ct)
   at DotNet.Testcontainers.Clients.TestcontainersClient.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
   at DotNet.Testcontainers.Containers.TestcontainersContainer.Create(CancellationToken ct)
   at DotNet.Testcontainers.Containers.TestcontainersContainer.StartAsync(CancellationToken ct)
```

**To Reproduce**
1. Create 8x tests PostgreSqlTest  from you examples and run
```
public sealed class PostgreSqlTest : IAsyncLifetime
{
  private readonly TestcontainerDatabase testcontainers = new TestcontainersBuilder<PostgreSqlTestcontainer>()
    .WithDatabase(new PostgreSqlTestcontainerConfiguration
    {
      Database = "db",
      Username = "postgres",
      Password = "postgres",
    })
    .Build();

  [Fact]
  public void ExecuteCommand()
  {
    using (var connection = new NpgsqlConnection(this.testcontainers.ConnectionString))
    {
      using (var command = new NpgsqlCommand())
      {
        connection.Open();
        command.Connection = connection;
        command.CommandText = "SELECT 1";
        command.ExecuteReader();
      }
    }
  }

  public Task InitializeAsync()
  {
    return this.testcontainers.StartAsync();
  }

  public Task DisposeAsync()
  {
    return this.testcontainers.DisposeAsync().AsTask();
  }
}
```

**Expected behavior**
No exception

**Desktop:**
Testcontainers: 2.1.0
OS: amd64 Linux 22.04.1 LTS (Jammy Jellyfish)
Docker: 20.10.18

**Comment by HofmeisterAn** [comment]
How do you create the test instances? One after another? Parallel? In the same process? Can you test the latest snapshot release `2.2.0-beta.3123645733`?

**Comment by raman-kazhadub** [comment]
> How do you create the test instances? One after another? Parallel? In the same process? Can you test the latest snapshot release `2.2.0-beta.3123645733`?

Run tests via
dotnet test command https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-test
In is the same process

**Comment by raman-kazhadub** [comment]
@HofmeisterAn
I have tested with 2.2.0-beta.3123645733. It is good now, thanks!

**Comment by HofmeisterAn** [comment]
I will close it then. Do not hesitate to reopen it again.
