### ISSUE TITLE
ResourceReaperException in CI/CD environment

### ISSUE THREAD

**Issue by jmsanchezapps** [testcontainers/testcontainers-dotnet#624]
**Describe the bug**
In my local environment I launch the tests without problem but in CI/CD environment where we launch the tests on a docker image  and docker in docker enabled in the host I get the following error:

`DotNet.Testcontainers.Containers.ResourceReaperException : Initialization has been cancelled.
StackTrace:    at DotNet.Testcontainers.Containers.ResourceReaper.GetAndStartNewAsync(Guid sessionId, IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, String ryukImage, TimeSpan initTimeout, CancellationToken ct) at DotNet.Testcontainers.Containers.ResourceReaper.GetAndStartNewAsync(Guid sessionId, IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, String ryukImage, TimeSpan initTimeout, CancellationToken ct) at DotNet.Testcontainers.Containers.ResourceReaper.GetAndStartDefaultAsync(IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, CancellationToken ct)
   at DotNet.Testcontainers.Clients.TestcontainersClient.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
   at DotNet.Testcontainers.Containers.TestcontainersContainer.Create(CancellationToken ct)
   at DotNet.Testcontainers.Containers.TestcontainersContainer.StartAsync(CancellationToken ct)
   at Tools_Core_Api_Tests.IntegrationTests.ContainerIntegrationTest.LoadData() in /datos/workspace/tools_tools-core_pipelines_developdeploy/Tools-Core/Tools-Core-Api-Tests/IntegrationTests/ContainerIntegrationTest.cs:line 28
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func1 invoke)
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUpOrTearDownMethod(TestExecutionContext context, IMethodInfo method)
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUp(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.OneTimeSetUpCommand.<>c__DisplayClass0_0.<.ctor>b__0(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeTestCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeTestCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformOneTimeSetUp()`

I have tried to update the version of TestContainers to the one indicated in this [issue](https://github.com/testcontainers/testcontainers-dotnet/issues/620) but now both locally and in the CI environment I get the error:

` Docker.DotNet.DockerApiException : Docker API responded with status code=Conflict, response={"message":"Container 239e3824a1de91cab903aeecc070440ab3a7df503965e421539e6c6fefb2a7af is not running"}
StackTrace:    at Docker.DotNet.DockerClient.HandleIfErrorResponseAsync(HttpStatusCode statusCode, HttpResponseMessage response, IEnumerable1 handlers)
   at Docker.DotNet.DockerClient.MakeRequestAsync(IEnumerable1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary2 headers, TimeSpan timeout, CancellationToken token)
   at Docker.DotNet.ExecOperations.ExecCreateContainerAsync(String id, ContainerExecCreateParameters parameters, CancellationToken cancellationToken)
   at DotNet.Testcontainers.Clients.DockerContainerOperations.ExecAsync(String id, IList1 command, CancellationToken ct)
   at DotNet.Testcontainers.Configurations.UntilUnixCommandIsCompleted.Until(ITestcontainersContainer testcontainers, ILogger logger)
   at DotNet.Testcontainers.Containers.TestcontainersContainer.<>c__DisplayClass35_1.<<Start>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at DotNet.Testcontainers.Configurations.WaitStrategy.<>c__DisplayClass1_0.<<WaitUntil>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at DotNet.Testcontainers.Configurations.WaitStrategy.WaitUntil(Func1 wait, Int32 frequency, Int32 timeout, CancellationToken ct)
   at DotNet.Testcontainers.Containers.TestcontainersContainer.Start(String id, CancellationToken ct)
   at DotNet.Testcontainers.Containers.TestcontainersContainer.StartAsync(CancellationToken ct)`

I don't know how to solve this.

**To Reproduce**
I'm using a base clase for tests using Nunit framework in this way:

`[SetUpFixture]
    internal class OracleContainerTest : WebApplicationFactory<Program>
    {
        internal static HttpClient Client;

        internal static WebApplicationFactory<Program> Factory;

        private static readonly TestcontainerDatabase oracleTestContainer = new TestcontainersBuilder<OracleTestcontainer>()
            .WithDatabase(new OracleTestcontainerConfiguration())
            .Build();

        public ContainerIntegrationTest()
        {
        }

        [OneTimeSetUp]
        public async Task LoadData()
        {
            await oracleTestContainer.StartAsync();

            Factory = new IntegrationTestWebApplicationFactory(oracleTestContainer);
            Client = Factory.CreateClient();

            Utilities.InitializeDbForTests(oracleTestContainer);
        }

        [OneTimeTearDown]
        public async Task DisposeContainer()
        {
            await oracleTestContainer.DisposeAsync().AsTask();
        }
    }`

**Expected behavior**

I want to be able to launch the tests without exceptions in both environments

**Desktop:**
Testcontainers: 2.1.0
OS: Windows 11
Docker Desktop 4.12.0

CI environment
Docker Server Version: 19.03.12
Kernel Version: 4.19.0-9-amd64
Operating System: Debian GNU/Linux 10 (buster)
docker image:  debian:11-slim

Thanks

**Comment by HofmeisterAn** [comment]
The Oracle configuration requires at least a password. Your snippet cannot work. Also the class name and constructor does not match. Does your CI environment have the Unix socket `/var/run/docker.sock`?

**Comment by jmsanchezapps** [comment]
yes, it has the socket. It hasn't problem with testcontainers-java in java projects.

Sorry, I wrote wrong code. Although I think the important part could be the oracle configuration. In the first case that I commented the configuration was:

`private static readonly TestcontainerDatabase oracleTestContainer = new TestcontainersBuilder<OracleTestcontainer>()
        .WithDatabase(new OracleTestcontainerConfiguration())
        .Build();`

and it worked perfectly in local but no in CI environment (`DotNet.Testcontainers.Containers.ResourceReaperException : Initialization has been cancelled`). 

After I tried with `"2.2.0-beta.3123645733"` version and yes, I set the password, this was the config:

`private static readonly TestcontainerDatabase oracleTestContainer = new TestcontainersBuilder<OracleTestcontainer>()
            .WithDatabase(new OracleTestcontainerConfiguration() { Password = Guid.NewGuid().ToString() })
            .Build();`

and it failed in both environments with the same exception (`Docker.DotNet.DockerApiException : Docker API responded with status code=Conflict, response={"message":"Container 239e3824a1de91cab903aeecc070440ab3a7df503965e421539e6c6fefb2a7af is not running"}`)

**Comment by HofmeisterAn** [comment]
Can you take a look into the Docker container logs? For some reason the container dies at the start. That is why you get:

> Container 239e3824a1de91cab903aeecc070440ab3a7df503965e421539e6c6fefb2a7af is not running

**Comment by jmsanchezapps** [comment]
yes, of course. I attach de log file, in this execution es for container `3eac277d7b314621a9fd5b160402a25b105f763ca93dbe6c9294e11c3c4c7483` in my local machine
[log.txt](https://github.com/testcontainers/testcontainers-dotnet/files/9840610/log.txt)

**Comment by HofmeisterAn** [comment]
I need the logs from the container too (the Oracle output).

**Comment by jmsanchezapps** [comment]
ohh, thanks for the clue! the problem was the value of the password that i was assigning `Password = Guid.NewGuid().ToString()`, in the container log I could see the real problem!

```
...
CONTAINER: Resetting SYS and SYSTEM passwords.
ALTER USER SYS    IDENTIFIED BY "47406670-deca-4aba-959a-cb1097efdb2c"
*
ERROR at line 1:
ORA-00972: identifier is too long
```

In local it work fine! I have to test this in CI environment but now I can't. When I do it I will give you feedback.

**Comment by jmsanchezapps** [comment]
Hi, the new version `"2.2.0-beta.3123645733"` is the solution, it works fine in my CI environment too! :)
Thanks @HofmeisterAn, 
good job wtih the library!
