### ISSUE TITLE
Azurite module unit test `AzuriteTestcontainerTest.AllServicesEnabled.ConnectionEstablished` fails

### ISSUE THREAD

**Issue by vlaskal** [testcontainers/testcontainers-dotnet#631]
**Describe the bug**
Azurite uni tests randomly fail with exception: `Azure.RequestFailedException: The configured endpoint Uri appears to contain the table name 'devstoreaccount1'. Please try re-creating the TableServiceClient with just the account Uri. For example: http://localhost:49181/.`

**To Reproduce**
1. Run Azurite unit test
2. 
```
2022-10-22 19:41:16.284 +02:00 [INF] DotNet.Testcontainers.Tests.Initialized Execute ["/bin/sh", "-c", "true && (cat /proc/net/tcp{,6} | awk '{print $2}' | grep -i :10000 || nc -vz -w 1 localhost 10000 || /bin/bash -c '</dev/tcp/localhost/10000')"] at Docker container "caf91710efb72aec90b0600d39496e1134b78cd02f52674dfb665201dc575197"
  Failed DotNet.Testcontainers.Tests.Unit.AzuriteTestcontainerTest+AllServicesEnabled.ConnectionEstablished [317 ms]
  Error Message:
   Assert.Null() Failure
Expected: (null)
Actual:   Azure.RequestFailedException: The configured endpoint Uri appears to contain the table name 'devstoreaccount1'. Please try re-creating the TableServiceClient with just the account Uri. For example: http://localhost:49181/.
           ---> Azure.RequestFailedException: Service request failed.
          Status: 403 (Server failed to authenticate the request.Make sure the value of the Authorization header is formed correctly including the signature.)
          
          Content:
          <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
          <Error>
            <Code>AuthorizationFailure</Code>
            <Message>Server failed to authenticate the request.Make sure the value of the Authorization header is formed correctly including the signature.
          RequestId:d0e7a250-6f2f-4a98-b6ed-07234a42649a
          Time:2022-10-22T17:41:15.573Z</Message>
          </Error>
          
          Headers:
          Server: Azurite-Queue/3.18.0
          x-ms-error-code: REDACTED
          x-ms-request-id: d0e7a250-6f2f-4a98-b6ed-07234a42649a
          x-ms-version: REDACTED
          Date: Sat, 22 Oct 2022 17:41:15 GMT
          Connection: keep-alive
          Keep-Alive: REDACTED
          Transfer-Encoding: chunked
          Content-Type: application/xml
          
             at Azure.Data.Tables.ServiceRestClient.GetPropertiesAsync(Nullable`1 timeout, CancellationToken cancellationToken)
             at Azure.Data.Tables.TableServiceClient.GetPropertiesAsync(CancellationToken cancellationToken)
             --- End of inner exception stack trace ---
             at Azure.Data.Tables.TableServiceClient.ValidateServiceUriDoesNotContainTableName(Exception ex, String tableName)
             at Azure.Data.Tables.TableServiceClient.GetPropertiesAsync(CancellationToken cancellationToken)
             at DotNet.Testcontainers.Tests.Unit.AzuriteTestcontainerTest.AllServicesEnabled.EstablishConnection(AzuriteDefaultFixture azurite) in /home/runner/work/testcontainers-dotnet/testcontainers-dotnet/tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/Databases/AzuriteTestcontainerTest.cs:line 103
             at Xunit.Record.ExceptionAsync(Func`1 testCode) in /_/src/xunit.core/Record.cs:line 76
  Stack Trace:
     at DotNet.Testcontainers.Tests.Unit.AzuriteTestcontainerTest.AllServicesEnabled.ConnectionEstablished() in /home/runner/work/testcontainers-dotnet/testcontainers-dotnet/tests/Testcontainers.Tests/Unit/Containers/Unix/Modules/Databases/AzuriteTestcontainerTest.cs:line 84
--- End of stack trace from previous location ---
2022-10-22 19:41:17.394 +02:00 [INF] DotNet.Testcontainers.Tests.Initialized Execute ["/bin/sh", "-c", "true && (cat /proc/net/tcp{,6} | awk '{print $2}' | grep -i :10000 || nc -vz -w 1 localhost 10000 || /bin/bash -c '</dev/tcp/localhost/10000')"] at Docker container "caf91710efb72aec90b0600d39496e1134b78cd02f52674dfb665201dc575197"
```

**Expected behavior**
Azurite tests should pass.

**Source**
[https://github.com/testcontainers/testcontainers-dotnet/actions/runs/3304094881/jobs/5452789560#step:7:435](https://github.com/testcontainers/testcontainers-dotnet/actions/runs/3304094881/jobs/5452789560#step:7:435)

**Comment by vlaskal** [comment]
@HofmeisterAn  I have tested to run just that specific test 100-times in a row and no fail and 100-times all of them and no fail. System was Windows + Docker desktop (WSL). Second test was on Ubuntu Desktop - there were some problems with volume bindings (is it tested od dekstop? Or is there any specific setup for ubuntu CI agent?) and again test passes only that binding problem happen on different tests. 

**Is there any other run which failed on same error?**

Based on the logs and TableClientService class implementation it look like that request response was error and based on it it look at if the dev account is part of url which is correct state. But table service client tried to connect to Queue service instead of Table service. This can happen only by port changing.
I see these next steps:
* try rerun of the failed run to see result
* collect other runs and investigate more
* split the test more (even code will be duplicated) to see if there is no setup issue and logs also container logs to output.
* fixed all other issues on Ubuntu Desktop 20.04 LTS with .NET 6.0 to be able to run in locally for longer time than 100 times.

What do you think?

**Comment by HofmeisterAn** [comment]
It looks like it accesses the wrong service: `Server: Azurite-Queue/3.18.0`. I prepared a branch to test it with the GitHub-hosted runner.

**Comment by vlaskal** [comment]
Yes, this is correct base on the logs. I suggest to rerun it and monitor it. And in case if it will not appear anymore then close this ticket and just monitor it.

**Comment by HofmeisterAn** [comment]
I run both tests after another, and it looks like both containers are affected. Even a third Azurite container fails.

- https://github.com/testcontainers/testcontainers-dotnet/actions/runs/3377081304/jobs/5605583210#step:7:643
- https://github.com/testcontainers/testcontainers-dotnet/actions/runs/3377081304/jobs/5605583210#step:7:376
