### ISSUE TITLE
⚠️ Fails to create `MySqlTestcontainer` with Docker 4.13.0 (89412)

### ISSUE THREAD

**Issue by macalbert** [testcontainers/testcontainers-dotnet#634]
Hi! 
After updating the version of Docker from 4.12 to 4.13, I can't start the container `MySqlTestcontainer`, and an exception like the following is thrown:

```
Did not expect any exception, but found Newtonsoft.Json.JsonReaderException with message "Error parsing undefined value. Path '', line 1, position 2."
     at Newtonsoft.Json.JsonTextReader.MatchAndSetAsync(String value, JsonToken newToken, Object tokenValue, CancellationToken cancellationToken)
     at Newtonsoft.Json.JsonTextReader.ParseValueAsync(CancellationToken cancellationToken)
     at Docker.DotNet.Models.StreamUtil.MonitorStreamForMessagesAsync[T](Task`1 streamTask, DockerClient client, CancellationToken cancellationToken, IProgress`1 progress)
     at Docker.DotNet.Models.StreamUtil.MonitorResponseForMessagesAsync[T](Task`1 responseTask, DockerClient client, CancellationToken cancel, IProgress`1 progress)
     at DotNet.Testcontainers.Clients.DockerImageOperations.CreateAsync(IDockerImage image, IDockerRegistryAuthenticationConfiguration dockerRegistryAuthConfig, CancellationToken ct)
     at DotNet.Testcontainers.Clients.TestcontainersClient.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
     at DotNet.Testcontainers.Containers.TestcontainersContainer.Create(CancellationToken ct)
     at DotNet.Testcontainers.Containers.TestcontainersContainer.StartAsync(CancellationToken ct)
     at Onclusive.Shared.Tests.DbContainerTest.<>c__DisplayClass0_0.<<Should_CreateDbContainer_When_ConfigurationIsValid>b__0>d.MoveNext() in C:\Users\kantar\source\repos\Onclusive\Shared\test\Shared.Tests\DbContainer.cs:line 23
  --- End of stack trace from previous location ---
     at FluentAssertions.Specialized.AsyncFunctionAssertions`2.NotThrowAsync(String because, Object[] becauseArgs)
.

  Stack Trace: 
XUnit2TestFramework.Throw(String message)
TestFrameworkProvider.Throw(String message)
DefaultAssertionStrategy.HandleFailure(String message)
AssertionScope.FailWith(Func`1 failReasonFunc)
AssertionScope.FailWith(Func`1 failReasonFunc)
AssertionScope.FailWith(String message, Object[] args)
DelegateAssertionsBase`2.NotThrowInternal(Exception exception, String because, Object[] becauseArgs)
AsyncFunctionAssertions`2.NotThrowAsync(String because, Object[] becauseArgs)
DbContainerTest.Should_CreateDbContainer_When_ConfigurationIsValid() line 26
--- End of stack trace from previous location ---

```

**To Reproduce**
```csharp
using DotNet.Testcontainers.Builders;
using DotNet.Testcontainers.Configurations;
using DotNet.Testcontainers.Containers;
using FluentAssertions;
using Xunit;

public class DbContainerTest
{
    [Fact]
    public async Task Should_CreateDbContainer_When_ConfigurationIsValid()
    {
        // Arrange
        var container = new TestcontainersBuilder<MySqlTestcontainer>()
            .WithDatabase(new MySqlTestcontainerConfiguration()
            {
                Database = "db",
                Username = "course",
                Password = "whatever"
            })
           .Build();

        // Act
        var action = async () => await container.StartAsync();

        // Assert
        await action.Should().NotThrowAsync();
    }
}
```

**Desktop:**
- Version 4.13.0 (89412)

**Comment by HofmeisterAn** [comment]
I can confirm [Docker.DotNet](https://github.com/dotnet/Docker.DotNet) fail with Docker Desktop 4.13.0. I created https://github.com/dotnet/Docker.DotNet/issues/595 and will start to take a look into it.

**Comment by HofmeisterAn** [comment]
I added a workaround until the upstream issue is identified and fixed. Anyone that relies on Docker Desktop 4.13.0 can use `2.2.0-beta.3311860540` or the upcoming `2.2.0`.
