### ISSUE TITLE
Better exception message when docker isn't running.

### ISSUE THREAD

**Issue by worldspawn** [testcontainers/testcontainers-dotnet#664]
If I forget to start docker before running tests I get this gem:

```
System.TypeInitializationException: The type initializer for 'DotNet.Testcontainers.Configurations.TestcontainersSettings' threw an exception.

System.TypeInitializationException
The type initializer for 'DotNet.Testcontainers.Configurations.TestcontainersSettings' threw an exception.
   at DotNet.Testcontainers.Configurations.TestcontainersSettings.set_Logger(ILogger value)
   at DBCloud.IntegrationTests.New.Fixtures.EndToEndTestsFixture..ctor(IMessageSink diagnosticMessageSink) in C:\Users\SamCritchley\source\bullclip-backend\DBCloud.IntegrationTests.New\Fixtures\EndToEndTestsFixture.cs:line 76

System.InvalidOperationException
Sequence contains no elements
   at System.Linq.ParallelEnumerable.GetOneWithPossibleDefault[TSource](QueryOperator`1 queryOp, Boolean throwIfTwo, Boolean defaultIfEmpty)
   at System.Linq.ParallelEnumerable.First[TSource](ParallelQuery`1 source)
   at DotNet.Testcontainers.Configurations.TestcontainersSettings..cctor()
```

Surely we could better. eg. Docker not found, docker not running, Yer docker be farked etc.

**Comment by worldspawn** [comment]
Never mind. I see its FirstOrDefault now, i'm obviously on an older build

**Comment by HofmeisterAn** [comment]
The latest versions checks the Docker endpoint configuration here:

https://github.com/testcontainers/testcontainers-dotnet/blob/4417c89e6a178916251a7481e6210cdb50e6321c/src/Testcontainers/Builders/TestcontainersBuilder.cs#L347-L348

and throws:

    Cannot detect the Docker endpoint. Use either the environment variables or the ~/.testcontainers.properties file to customize your configuration:\nhttps://www.testcontainers.org/features/configuration/#customizing-docker-host-detection
