### ISSUE TITLE
Can't satrt MariaDB container, hangs on StartAsync

### ISSUE THREAD

**Issue by Hertzole** [testcontainers/testcontainers-dotnet#676]
**Describe the bug**
I'm trying to start a MariaDB container but it always seem to hang on the StartAsync and Docker.DotNet eventually returns an error, failing the tests before they even start.

**Code snippets**
I use a WebApplicationFactory for my tests.  
```cs
public class ApiWebApplicationFactory : WebApplicationFactory<Program>, IAsyncLifetime
{
	private readonly MariaDbTestcontainer dbContainer =
		new TestcontainersBuilder<MariaDbTestcontainer>()
			.WithDatabase(new MariaDbTestcontainerConfiguration()
			{
				Database = "testdb",
				Username = "root",
				Password = "example"
			}).Build();

	protected override void ConfigureWebHost(IWebHostBuilder builder)
	{		
		builder.ConfigureTestServices(services =>
		{
			services.RemoveAll(typeof(DbContextFactory<AppDbContext>));
			services.AddDbContextFactory<AppDbContext>(optionsBuilder =>
			{
				optionsBuilder.UseMySql(dbContainer.ConnectionString, 
ServerVersion.AutoDetect(dbContainer.ConnectionString));
			});
		});
	}

	public Task InitializeAsync()
	{
		return dbContainer.StartAsync(); // Hangs here
	}

	public new Task DisposeAsync()
	{
		return dbContainer.StopAsync();
	}
}
```
And then use it like so
```cs
public class Tests : IClassFixture<ApiWebApplicationFactory>
{
	private readonly ApiWebApplicationFactory factory;

	public Tests(ApiWebApplicationFactory factory)
	{
		this.factory = factory;
	}

	// tests here...
}
```

When running the tests, it will never get past the `InitializeAsync` method and will eventually return this error:
```
Docker.DotNet.DockerApiException
Docker API responded with status code=Conflict, response={"message":"Container blabla is not running"}

   at Docker.DotNet.DockerClient.HandleIfErrorResponseAsync(HttpStatusCode statusCode, HttpResponseMessage response, IEnumerable`1 handlers)
   at Docker.DotNet.DockerClient.MakeRequestAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
   at Docker.DotNet.ExecOperations.ExecCreateContainerAsync(String id, ContainerExecCreateParameters parameters, CancellationToken cancellationToken)
   at DotNet.Testcontainers.Clients.DockerContainerOperations.ExecAsync(String id, IList`1 command, CancellationToken ct)
   at DotNet.Testcontainers.Configurations.UntilUnixCommandIsCompleted.Until(ITestcontainersContainer testcontainers, ILogger logger)
   at DotNet.Testcontainers.Containers.TestcontainersContainer.<>c__DisplayClass37_1.<<Start>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at DotNet.Testcontainers.Configurations.WaitStrategy.<>c__DisplayClass1_0.<<WaitUntil>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at DotNet.Testcontainers.Configurations.WaitStrategy.WaitUntil(Func`1 wait, Int32 frequency, Int32 timeout, CancellationToken ct)
   at DotNet.Testcontainers.Containers.TestcontainersContainer.Start(String id, CancellationToken ct)
   at DotNet.Testcontainers.Containers.TestcontainersContainer.StartAsync(CancellationToken ct)
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
```

The container is started in docker and I can't see any immediate red flags in the logs of the container that would give away any errors.

**Desktop**
- Version 2.2.0

**Additional context**
I also tried setting up the container manually by providing the config values myself but it just gave me the same result. I have not tested with any other types of images other than MariaDB as I'm still very new to both docker and databases and it's the only one I (semi) know how to use right now.

**Comment by HofmeisterAn** [comment]
If you look into the container logs, you will see following error:

    ERROR 1396 (HY000) at line 21: Operation CREATE USER failed for 'root'@'%'

You cannot create the `root` user, it already exists. Choose a different username.

**Comment by Hertzole** [comment]
Oh. I see that now. 🤦‍♂️   
Thank you for the help!
