### ISSUE TITLE
[Bug]: Could not load type 'DotNet.Testcontainers.Containers.MySqlTestcontainer

### ISSUE THREAD

**Issue by cactuar** [testcontainers/testcontainers-dotnet#745]
### Testcontainers version

2.3.0

### Using the latest Testcontainers version?

Yes

### Host OS

Windows

### Host arch

x86

### .NET version

4.8

### Docker version

```shell
Client:
 Cloud integration: v1.0.29
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:36:18 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.16.2 (95914)
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:26:14 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.0)
  compose: Docker Compose (Docker Inc., v2.15.1)
  dev: Docker Dev Environments (Docker Inc., v0.0.5)
  extension: Manages Docker extensions (Docker Inc., v0.2.17)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.16.3-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 24.82GiB
 Name: docker-desktop
 ID: IWBG:WO4W:LGZG:O3D5:VY3S:BMDN:ZNCY:ETSC:MC4T:227X:52FO:J2PD
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

### What happened?

Hello,
sorry if I didn't find the correct information, but I believed TestContainers should work even with .net 4.8 (it should support .net standard 2.0, right?)
This minimal example works fine in a .net 7 solution, while it fails with a TypeLoadException with a 4.8 one.
Am I missing something?

Sorry again if it's a big mistake on my end. Thank you very much!

### Relevant log output

```shell
System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'DotNet.Testcontainers.Containers.MySqlTestcontainer' from assembly 'TestContainers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
  Source=TestContainers
  StackTrace:
   at TestContainers.Program.<Main>d__0.MoveNext() in C:\Projects\TestContainers\TestContainers\Program.cs:line 40
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\AsyncMethodBuilder.cs:line 316
   at TestContainers.Program.Main(String[] args) in C:\Projects\TestContainers\TestContainers\Program.cs:line 15
   at TestContainers.Program.<Main>(String[] args)
```

### Additional information

 ```
       static async Task Main(string[] args)
        {
            var _container = new TestcontainersBuilder<MySqlTestcontainer>()
                .WithAutoRemove(true)
                .WithDatabase(new MySqlTestcontainerConfiguration
                {
                    Password = "123testPassword!",
                    Database = "testdb",
                })
                .WithImage("mysql:latest")
                .WithPortBinding(3306, true) // port is automatically assigned
                .WithName("testcontainer-integration-" + Guid.NewGuid().ToString().Replace("-", ""))
                .WithTmpfsMount("/var/opt/mssql/data")
                .WithTmpfsMount("/var/opt/mssql/log")
                .Build();
            await _container.StartAsync().ConfigureAwait(false);
        }
    }
```

**Comment by cactuar** [comment]
Sorry, just recreated once again the solution and it works like a charm :-)
